In [2]:
import os
import numpy as np
import cv2
resize_width = 100
resize_height = 100
path = 'scans'
images = [] # List to append the images as 2D numpy arrays.
target = [] # List to append the target
originalrepo = [] # Create a repo for flattened pixels

for root, dirs, files in os.walk(path):
     for file in files:
        with open(os.path.join(root, file), "r") as auto:
            try:
                img = cv2.imread(root+'/'+file, 0)
                img = cv2.resize(img, (resize_width, resize_height)) 
                images.append(img)
                # Append the flattened image to the pixel repo
                originalrepo.append(img.flatten())
                # Append the folder where the image is to the target list
                target.append(root.replace(path,'').replace('\\','').replace('/',''))
            except Exception as e:
                print("Invalid file "+file+" skipped.")
# Convert the repo list into numpy array
originalrepo = np.array(originalrepo) 
print(originalrepo)
print(target)

Invalid file .DS_Store skipped.
Invalid file .DS_Store skipped.
Invalid file .DS_Store skipped.
Invalid file 26 copy 3.jpg skipped.
Invalid file .DS_Store skipped.
Invalid file 2 copy 4.jpg skipped.
Invalid file 0 copy 3.jpg skipped.


libpng warning: bKGD: invalid


[[ 40 201  13 ...  24  24  24]
 [145  99  24 ...  18  19  19]
 [ 21  22  20 ...  26  29  45]
 ...
 [133 151 132 ...  98  98  99]
 [  0   0   0 ...   0   0   0]
 [ 10  10  10 ...  10  10  10]]
['chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xray', 'chest_xr

Files retrieved from:

https://www.kaggle.com/danialsharifrazi/cad-cardiac-mri-dataset

https://www.kaggle.com/tommyngx/hand-fracture-mini-model

https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia

******************************************************************

Name: Cobblah Hemade


ID:   2119970

Course Work 1

In [ ]:
files i have in a class